@extends("theme/$theme/layaut")
@section('content') 
<table style="text-align: center;" class="table table-bordered">
    <tr >
        <td colspan="2"  class="table-info">
            <h3 style="text-align:center;color: #000033; font-weight: bold;margin-top:2%;"> 
                 Datos de cantidad de suegreros por ciudad
            </h3>
        </td>
    </tr>
    <tr>
        <th  style="text-align: center;">CIUDAD</th>
        <th  style="text-align: center;">CANTIDAD</th>
    </tr>
    <tr>
        <td>Madrid</td>
        <td>{{$c1}}</td>
    </tr>
    <tr>
        <td>Barcelona</td>
        <td>{{$c2}}</td>
    </tr>
    <tr>
        <td>Valencia</td>
        <td>{{$c3}}</td>
    </tr>
    <tr>
        <td>Sevilla</td>
        <td>{{$c4}}</td>
    </tr>
    <tr>
        <td>Zaragoza</td>
        <td>{{$c5}}</td>
    </tr>
    <tr>
        <td>Málaga</td>
        <td>{{$c6}}</td>
    </tr>
    <tr>
        <td>Murcia</td>
        <td>{{$c7}}</td>
    </tr>
    <tr>
        <td>Palma</td>
        <td>{{$c8}}</td>
    </tr>
    <tr>
        <td>Bilbao</td>
        <td>{{$c9}}</td>
    </tr>
    <tr>
        <td>Alicante</td>
        <td>{{$c10}}</td>
    </tr>
    <tr>
        <td>Córdoba</td>
        <td>{{$c11}}</td>
    </tr>
    <tr>
        <td>Valladolid</td>
        <td>{{$c12}}</td>
    </tr>
    <tr>
        <td>Vitoria</td>
        <td>{{$c13}}</td>
    </tr>
    <tr>
        <td>La Coruña</td>
        <td>{{$c14}}</td>
    </tr>
    <tr>
        <td>Granada</td>
        <td>{{$c15}}</td>
    </tr>
    <tr>
        <td>Oviedo</td>
        <td>{{$c16}}</td>
    </tr>
    <tr>
        <td>Santa Cruz</td>
        <td>{{$c17}}</td>
    </tr>
    <tr>
        <td>Pamplona</td>
        <td>{{$c18}}</td>
    </tr>
    <tr>
        <td>Almería</td>
        <td>{{$c19}}</td>
    </tr>
    <tr>
        <td>Burgos</td>
        <td>{{$c20}}</td>
    </tr>
    <tr>
        <td>Albacete</td>
        <td>{{$c21}}</td>
    </tr>
    <tr>
        <td>Santander</td>
        <td>{{$c22}}</td>
    </tr>
    <tr>
        <td>Castellón de la Plana</td>
        <td>{{$c23}}</td>
    </tr>
    <tr>
        <td>Logroño</td>
        <td>{{$c24}}</td>
    </tr>
    <tr>
        <td>Badajoz</td>
        <td>{{$c25}}</td>
    </tr>
    <tr>
        <td>Huelva</td>
        <td>{{$c26}}</td>
    </tr>
    <tr>
        <td>Salamanca</td>
        <td>{{$c27}}</td>
    </tr>
    <tr>
        <td>Lérida</td>
        <td>{{$c28}}</td>
    </tr>
    <tr>
        <td>Tarragona</td>
        <td>{{$c29}}</td>
    </tr>
    <tr>
        <td>León</td>
        <td>{{$c30}}</td>
    </tr>
    <tr>
        <td>Cádiz</td>
        <td>{{$c31}}</td>
    </tr>
    <tr>
        <td>Jaén</td>
        <td>{{$c32}}</td>
    </tr>
    <tr>
        <td>Orense</td>
        <td>{{$c33}}</td>
    </tr>
    <tr>
        <td>Gerona</td>
        <td>{{$c34}}</td>
    </tr>
    <tr>
        <td>Lugo</td>
        <td>{{$c35}}</td>
    </tr>
    <tr>
        <td>Santiago de Compostela</td>
        <td>{{$c36}}</td>
    </tr>
    <tr>
        <td>Cáceres</td>
        <td>{{$c37}}</td>
    </tr>
    <tr>
        <td>CáMelilla</td>
        <td>{{$c38}}</td>
    </tr>
    <tr>
        <td>Ceuta</td>
        <td>{{$c39}}</td>
    </tr>
    <tr>
        <td>Guadalajara</td>
        <td>{{$c40}}</td>
    </tr>
    <tr>
        <td>Toledo</td>
        <td>{{$c41}}</td>
    </tr>
    <tr>
        <td>Pontevedra</td>
        <td>{{$c42}}</td>
    </tr>
    <tr>
        <td>Palencia</td>
        <td>{{$c43}}</td>
    </tr>
    <tr>
        <td>Ciudad Real</td>
        <td>{{$c44}}</td>
    </tr>
    <tr>
        <td>Zamora</td>
        <td>{{$c45}}</td>
    </tr>
    <tr>
        <td>Mérida</td>
        <td>{{$c46}}</td>
    </tr>
    <tr>
        <td>Ávila</td>
        <td>{{$c47}}</td>
    </tr>
    <tr>
        <td>Cuenca</td>
        <td>{{$c48}}</td>
    </tr>
    <tr>
        <td>Huesca</td>
        <td>{{$c49}}</td>
    </tr>
    <tr>
        <td>Segovia</td>
        <td>{{$c50}}</td>
    </tr>
    <tr>
        <td>Soria</td>
        <td>{{$c51}}</td>
    </tr>
    <tr>
        <td>Teruel</td>
        <td>{{$c52}}</td>
    </tr>
    <tr>
        <td>San Sebastián</td>
        <td>{{$c53}}</td>
    </tr>
  </table>
 
  @endsection